### ISSUE TITLE
GNSS data of M2DGR

### ISSUE THREAD

**Issue by Lchhehehe** [SJTU-ViSYS/M2DGR#17]
1)The M2DGR literature points out that there are two GNSS receivers' data, but I see that the schematic diagram has only one antenna. Do the two receivers share the same antenna, one of which records the original observation and the other records the real trajectory?
2)Can you provide documents such as the format description of topic, or where you can find such documents? It seems that the topic description file on the ROS official website does not contain the description of the raw observations of GNSS.
3)The operation of converting rosbag (street_02.bag) into GNSS raw observation data through the ublox2rinex program failed, and only the header file of RINEX was generated.

**Comment by Lchhehehe** [comment]
![图片](https://user-images.githubusercontent.com/102840022/161361065-b5469b19-72da-4904-95e4-836b4bfaa3f9.png)

**Comment by sjtuyinjie** [comment]
(1). Yes, GNSS signals are received by  a single antenna and shared to two GNSS receivers by a power splitter.
(2). You can look up to GNSS raw observation.
(3).You may need to  slightly modify the configuration like changing the file path. I am sure the toolkit can successfully convert Rosbag to GNSS raw observation data because I have done it before.

**Comment by impce-lg** [comment]
Is the GNSS obs single frequency or double frequencies?

**Comment by impce-lg** [comment]
The paper shows the GNSS freq is 1Hz, but I got 4Hz (0.25s interval), is there something wrong?
