### ISSUE TITLE
VI-Sensor d435i depth data?

### ISSUE THREAD

**Issue by xingjing** [SJTU-ViSYS/M2DGR#29]
Thanks for your great work!
I have a question that from your paper and readme I noticed that Intel Realsense d435i is used to collect RGB and IMU data.  But there is no mention of depth image. I wonder if you recorded the depth image data.  I'm looking for SLAM dataset with depth and fisheye image.

**Comment by sjtuyinjie** [comment]
I used to try collecting depth information of D435I along with all other sensory information, but this sensor will drop depth frames frequently when the USB port is with  heavy load . Therefore, as indicated in my paper, I did not collect depth information in this public dataset. 
Bedsides, I'd like to remind you that the depth frame is aligned with pinhole frame instead of the fisheye frame in D435I.
